wandb_version: 1

wandb:
  desc: null
  value: true
batch_size:
  desc: null
  value: 2048
learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 1000
validation_interval:
  desc: null
  value: 10
checkpoint_file_path:
  desc: null
  value: /data/2_data_server/nlp-05/KOREATECH/2024-2_DL/link_dl/_03_your_code/CSE533/hw3/checkpoints
early_stop_patience:
  desc: null
  value: 5
early_stop_delta:
  desc: null
  value: 0.001
validation_intervals:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.18.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1732368457
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 2
      - 13
      - 15
      - 16
      - 55
      4: 3.10.14
      5: 0.18.5
      8:
      - 1
      - 5
      13: linux-x86_64
