wandb_version: 1

wandb:
  desc: null
  value: true
batch_size:
  desc: null
  value: 2048
learning_rate:
  desc: null
  value: 0.001
validation_interval:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.18.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1732367001
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 2
      - 15
      - 16
      - 55
      4: 3.10.14
      5: 0.18.5
      8:
      - 1
      - 5
      13: linux-x86_64
